/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.channels.FileChannel;
import java.nio.file.Path;

  //  import java.lang.Object.org.apache.commons.io.FileUtils;//

/**
 *
 * @author ameya
 */
public class ReceiverCertificate extends javax.swing.JFrame {

    String sender_name;
    /**
     * Creates new form ReceiverCertificate
     */
    public ReceiverCertificate() {
        initComponents();
    }

    ReceiverCertificate(String name) {
        this.sender_name = name;
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Download");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Accept");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Reject");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Amount");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(jTextField3)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String Recipient_name = jTextField3.getText();
            int amount = new Integer(jTextField4.getText());
            OutputStream file = new FileOutputStream(new File(Recipient_name+"Response.pdf"));
            Document document = new Document();
	    PdfWriter.getInstance(document, file);

	            document.open();
	          //  document.add(new Paragraph("First iText PDF"));
	          //  document.add(new Paragraph(new Date().toString()));

	           /* document.addAuthor("Ameya");
	            document.addCreationDate();
	            document.addCreator("JavaBeat");
	            document.addTitle("Transaction");
                    */
                    Paragraph paragraph = new Paragraph();
                    Chunk chunk = new Chunk("Recipient's Name: "+Recipient_name);
                       paragraph.add(new Paragraph(" "));
		   // chunk.setUnderline(+1f,-2f);//1st co-ordinate is for line width,2nd is space between
		    Chunk chunk1 = new Chunk("Sender's Name: "+this.sender_name);
                       paragraph.add(new Paragraph(" "));
                     Chunk chunk2 = new Chunk("Amount: "+amount);
                        paragraph.add(new Paragraph(" "));
                        Chunk chunk3 = new Chunk("I accept the above transaction");  
                         paragraph.add(new Paragraph(" "));
		   // chunk1.setUnderline(+4f,-8f);
		   // chunk1.setBackground(new BaseColor (17, 46, 193));  
                    	document.add(chunk);
                        document.add(chunk1);
                        document.add(chunk2);
                        document.add(chunk3);
	            //     Font.BOLD));
                      paragraph.add(new Paragraph(" "));
	            //paragraph.add("Test Paragraph");
	            paragraph.add(new Paragraph(" "));
	            document.add(paragraph);

	            document.close();
	            file.close();
                
                    String currentDir = System.getProperty("user.dir");   
                    String current = currentDir+Recipient_name+"/SamplePDF.pdf";  
                    System.out.println("Current dir using System:" +current);  
                    File file_read = new File(currentDir );
                    if (file_read.exists()) {
                        Desktop desktop = Desktop.getDesktop();
                        if (desktop.isSupported(Desktop.Action.OPEN)) {
                           // if (Desktop.isDesktopSupported()) {
				Desktop.getDesktop().open(file_read);
                        } else {
				System.out.println("Awt Desktop is not supported!");
                        }
                    } else {    
 
			System.out.println("File is not exists");
 
                    }
 
		    System.out.println("Done");
                    File directory = new File(currentDir);
                File file_trans = new File(directory,"Transaction");
          
		if (!file_trans.exists()) 
                    file_trans.createNewFile();
                FileWriter fileWritter = new FileWriter(file_trans,true);
    	        BufferedWriter bufferWritter = new BufferedWriter(fileWritter);
    	        bufferWritter.write(Recipient_name+":"+amount);
    	        bufferWritter.close();
		
        }
        catch (NumberFormatException | DocumentException | IOException e) {
        }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try {
             String Recipient_name = jTextField3.getText();
         
            int amount = new Integer(jTextField4.getText());
  String currentDir = System.getProperty("user.dir");   
                    String current = currentDir+Recipient_name+"/SamplePDF.pdf";  
                    System.out.println("Current dir using System:" +current);  
                    File file_read = new File(currentDir );
                    if (file_read.exists()) {
                        Desktop desktop = Desktop.getDesktop();
                        if (desktop.isSupported(Desktop.Action.OPEN)) {
                           // if (Desktop.isDesktopSupported()) {
				Desktop.getDesktop().open(file_read);
                        } else {
				System.out.println("Awt Desktop is not supported!");
                        }
                    } else {    
 
			System.out.println("File is not exists");
 
                    }
 
		    System.out.println("Done");
                    
            OutputStream file = new FileOutputStream(new File(Recipient_name+"Response.pdf"));
            Document document = new Document();
	    PdfWriter.getInstance(document, file);

	            document.open();
	          //  document.add(new Paragraph("First iText PDF"));
	          //  document.add(new Paragraph(new Date().toString()));

	           /* document.addAuthor("Ameya");
	            document.addCreationDate();
	            document.addCreator("JavaBeat");
	            document.addTitle("Transaction");
                    */
                    Paragraph paragraph = new Paragraph();
                    Chunk chunk = new Chunk("Recipient's Name: "+Recipient_name);
                       paragraph.add(new Paragraph(" "));
		   // chunk.setUnderline(+1f,-2f);//1st co-ordinate is for line width,2nd is space between
		    Chunk chunk1 = new Chunk("Sender's Name: "+this.sender_name);
                       paragraph.add(new Paragraph(" "));
                     Chunk chunk2 = new Chunk("Amount: "+amount);
                        paragraph.add(new Paragraph(" "));
                        Chunk chunk3 = new Chunk("Sorry, I dont want to continue this above transaction");  
                         paragraph.add(new Paragraph(" "));
		   // chunk1.setUnderline(+4f,-8f);
		   // chunk1.setBackground(new BaseColor (17, 46, 193));  
                    	document.add(chunk);
                        document.add(chunk1);
                        document.add(chunk2);
                        document.add(chunk3);
	            //     Font.BOLD));
                      paragraph.add(new Paragraph(" "));
	            //paragraph.add("Test Paragraph");
	            paragraph.add(new Paragraph(" "));
	            document.add(paragraph);

	            document.close();
	            file.close();
    }//GEN-LAST:event_jButton3ActionPerformed
 catch(Exception e )
 {
 }
 }
    public static void copyFolder(File src, File dest)
    {
        try { 
    	if(src.isDirectory()){
 		if(!dest.exists()){
    		   dest.mkdir();
    		 
    		String files[] = src.list();
 
    		for (String file : files) {
    		  
    		   File srcFile = new File(src, file);
    		   File destFile = new File(dest, file);
    		   
    		   copyFolder(srcFile,destFile);
    		}
 
    	}else{
    		
    		InputStream in = new FileInputStream(src);
    	        OutputStream out = new FileOutputStream(dest); 
 
    	        byte[] buffer = new byte[1024];
 
    	        int length;
    	       
    	        while ((length = in.read(buffer)) > 0){
    	    	   out.write(buffer, 0, length);
    	        }
 
    	        in.close();
    	        out.close();
    	        
    	}
    }
        }
        catch(Exception e)
        {
                
        }
        }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        EmailDownload ed = new EmailDownload();
        dispose();
        ed.setVisible(true);
        
        
      /*  File srcFolder = new File("/home/ameya/Downloads/keys/");
        File destFolder = new File("/home/ameya/Mtech/learn/java/keys/");
        copyFolder(srcFolder,destFolder);
        String files[] = destFolder.list();
        for (String file : files) {
           // String fname = file.getName();
            int pos = file.lastIndexOf(".");
            if (pos > 0) 
                file = file.substring(0, pos);
        	BufferedReader br = new BufferedReader(new FileReader(info_file));
                String line;
                while ((line = br.readLine()) != null) {
                    if(!line.contains(file))
                    {
                        FileWriter fileWritter = new FileWriter(info_file,true);
                         bufferWritter = new BufferedWriter(fileWritter);
                        bufferWritter.write(file+":"+file+"publickey.txt");
                       
		                    }     		
            		
                }
                br.close();
         }
      */
        
    }        
catch(Exception e)
{
}     
        
    }//GEN-LAST:event_jButton1ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiverCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiverCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiverCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiverCertificate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceiverCertificate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
